version: '3.8'

services:
  studio-server:
    image: allebb/studio-server:latest
    container_name: studio-server
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
    ports:
      - "5432:5432"
      - "50059:50059"
      - "8543:8543"
    volumes:
      # These are now Named Volumes
      - studio_hooks:/var/studio-server/hooks/
      - studio_database:/var/studio-server/database/
      - studio_backups:/var/studio-server/backups/
      - studio_jobs:/etc/cron.d/

# Now we call them out at the bottom!
volumes:
  studio_hooks:
  studio_database:
  studio_backups:
  studio_jobs: